### ISSUE TITLE
How to test the SSL connection?

### ISSUE THREAD

**Issue by mgtdi** [rroemhild/docker-test-openldap#16]
Do you have the way to test it with the SSL/TLS connection? Maybe I am doing something wrong because I am getting this log error 

TLS: can't accept: A TLS fatal alert has been received..

If you have the line or the way I will really appreciate.

**Comment by jeloba** [comment]
How do you access the LDAP server? Maybe your client is rejecting the self signed cert, because it's not trusted or the cname is different?
