### ISSUE TITLE
Fix listen address

### ISSUE THREAD

**Issue by wollanup** [rroemhild/docker-test-openldap#23]
Please merge https://github.com/rroemhild/docker-test-openldap/pull/21 ASAP.

CI stages based on your latest image are broken, and we can't rollback, as only `latest` image is provided on DockerHub.

Thank you.

**Comment by liorhasson** [comment]
Our CI also broken!!!! ASAP
Also can you please publish docker tags for every release, then we can use specific version!

@rroemhild 
Thanks

**Comment by rroemhild** [comment]
Sorry folks! I've reverted the port changes too. Builds will be tagged in the future.

**Comment by wollanup** [comment]
Thank you @rroemhild 
Image tags would be great !
It was not a bad idea to use a port > 1024, maybe in a 2.0 tag as it's a breaking change ?

**Comment by wollanup** [comment]
Oh, I've just seen you change  ports again a few seconds ago :D
So we keep unprivilegied ports 10XXX, which sounds logical.

**Comment by rroemhild** [comment]
I've made it worse :D 

I add the tag `v1` to the latest commit/build before I've done major changes.

**Comment by wollanup** [comment]
OK, your latest commit sounds goot to me, with the new unprivilegied ports config `10389`, my CI stage pass.
May I suggest you to publish docker image `2.0` and `1.0` (as a fallback) on DockerHub for folks who can't update their code/config ? Maybe it's easier for some people to only add the target tag in a docker-compose file ?

**Comment by rroemhild** [comment]
Great! Tags are now on DockerHub.
