### ISSUE TITLE
What is the Group Search Base?

### ISSUE THREAD

**Issue by ManuelSimon** [rroemhild/docker-test-openldap#39]
User Search Base is "ou=people,dc=planetexpress,dc=com", but what is the one for Groups? It doesn't seem to be indicated in the readme file. Thanks!

**Comment by SpiGAndromeda** [comment]
The same like for users. They share the same ou.

**Comment by rroemhild** [comment]
Missed this issue. @SpiGAndromeda is right. You can do a "group search" with a filter.
