### ISSUE TITLE
Only anonymous authentication enabled ?

### ISSUE THREAD

**Issue by jamendub** [rroemhild/docker-test-openldap#4]
Hi, I'm trying to use you docker image to setup a quick ldap authentication !
I did successfully run a container and can access it's data when i login anonymously through phpLDAPadmin, though i cannot access it with my app because it requires a username and a password for the root DN.

Is there a way you could help me with that please ?
Thanks a lot for this repository and for you attention !

**Comment by rroemhild** [comment]
Hi, I can't reproduce your problem. Can you post any logs from the container? I've just tried the login with ldap-tools:

```
$ ldapwhoami  -v -x -h localhost
ldap_initialize( ldap://localhost )
anonymous
Result: Success (0)
```

```
$ ldapwhoami -v -x -h localhost -D "cn=Hermes Conrad,ou=people,dc=planetexpress,dc=com" -w hermes
ldap_initialize( ldap://localhost )
dn:cn=Hermes Conrad,ou=people,dc=planetexpress,dc=com
Result: Success (0)
```

**Comment by jamendub** [comment]
Hello, I will try to provide you with an example of what I'm trying to do and logs too.
Thanks for you quick answer !

**Comment by montetitan** [comment]
docker run --env LDAP_ORGANISATION="people" --env LDAP_DOMAIN="planetexpress.com" --env LDAP_ADMIN_PASSWORD="admin" --privileged -p 389:389 -p 636:636 --name my-openldap-container --detach rroemhild/test-openldap

how do i make 
ldapwhoami -v -x -h localhost -D "ou=people,dc=planetexpress,dc=com" -w hermes work? or any other user for that matter?

**Comment by rroemhild** [comment]
`-w` is the password for the user entry DN set with `-D`.

You have to use the DN from a user entry to login, i.e. for the user hermes:

```sh
ldapwhoami -v -x -h localhost -D "cn=Hermes Conrad,ou=people,dc=planetexpress,dc=com" -w hermes
```

for amy:

```
ldapwhoami -v -x -h localhost -D "cn=Amy Wong+sn=Kroker,ou=people,dc=planetexpress,dc=com" -w amy
```

**Comment by montetitan** [comment]
my issue is jxplorer gets the data via anonymous,
but if i give hermes/hermes or fry/fry via (user+password) it doesnt work,
any way to get it working for user+password?
<img width="794" alt="Screenshot 2020-06-11 at 9 13 20 PM" src="https://user-images.githubusercontent.com/34226152/84407495-8ea3f300-ac28-11ea-9489-029f7ef1a0e2.png">
attached screenshot as well,
anonymous gets me everything but im trying to login via the members and it fails

**Comment by rroemhild** [comment]
hermes ist not the User DN. hermes is the value of the attribute uid. If you want to authenticate with user+password you need to perform an ldap search (uid=hermes) to get the DN for the entry that matches the search and then authenticate with DN+password.
