### ISSUE TITLE
Trying to build image locally - bash error

### ISSUE THREAD

**Issue by anthonyMc11** [rroemhild/docker-test-openldap#41]
I'm trying to build the image locally for this project from the master branch, the only changes I've made is to the docker-compose file to simplify it:

`version: '2'`
`services:`
`    ldap:`
`        image: my-local-ldap`
`        build:`
`            context: ./`
`            dockerfile: ./Dockerfile`

When I try and run the resulting image I keep getting the following Error in the container logs:

: No such file or directory bash

 when trying to run the s6-overlay 

I've looked at the information on s6 and I've even trying upgrading to v3 but still getting this error, do you know how to get past it?
Below is the log output for the container

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 000-slapd-package-config: executing... 
: No such file or directory bash
[cont-init.d] 000-slapd-package-config: exited 127.
[cont-init.d] 010-tls-certificates: executing... 
: No such file or directory bash
[cont-init.d] 010-tls-certificates: exited 127.
[cont-init.d] 020-filesystem-perms: executing... 
: No such file or directory bash
[cont-init.d] 020-filesystem-perms: exited 127.
[cont-init.d] 050-openldap-populate: executing... 
: No such file or directory bash
[cont-init.d] 050-openldap-populate: exited 127.
[cont-init.d] done.
[services.d] starting services
: No such file or directory bash
[services.d] done.
: No such file or directory bash
: No such file or directory bash

**Comment by jcvegan** [comment]
Hello @anthonyMc11 I am facing the same issue, how did you solve it?

**Comment by anthonyMc11** [comment]
@jcvegan  the issue was I was using Windows. To fix it I opened the project in vscode and changed all the line endings to be cf. It then started working. I would've committed the fix, however github didn't recognise the line endings as a change
