### ISSUE TITLE
Slapd fails to start with new build image

### ISSUE THREAD

**Issue by paulkitt** [rroemhild/docker-test-openldap#42]
We build the actual state of the repo planing to make some small changes in the user/group structure.
When starting the image with no modifications slapd fails:
```
openldap             | 6310a7c3 @(#) $OpenLDAP: slapd  (May 14 2022 18:35:44) $
openldap             |  Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
openldap             | 6310a7c4 hdb_db_open: database "dc=planetexpress,dc=com": database already in use.
openldap             | 6310a7c4 backend_startup_one (type=hdb, suffix="dc=planetexpress,dc=com"): bi_db_open failed! (-1)
openldap             | 6310a7c4 slapd stopped.
```

**Comment by paulkitt** [comment]
Anybody manages to work with the current master? The project is great and it would be awesome to find a way to work with it.

**Comment by rroemhild** [comment]
This seems to be a problem with a previous error from ldapmodify while configure TLS:

```
Configure TLS...
+ ldapmodify -Y EXTERNAL -H ldapi:/// -f /opt/openldap/bootstrap/config/tls.ldif -Q
modifying entry "cn=config"
ldap_modify: Other (e.g., implementation specific) error (80)
```

The script exit early an does not shutdown the slapd process.

**Comment by jskacel** [comment]
Looks like the issue is because of missing `/etc/ldap/ssl/fullchain.crt`

**Comment by jskacel** [comment]
So.. if you remove these lines https://github.com/rroemhild/docker-test-openldap/blob/master/rootfs/opt/openldap/bootstrap/config/tls.ldif#L3-L5 and rebuild the image, it will start to work
