### ISSUE TITLE
ldapsearch 32 no such object

### ISSUE THREAD

**Issue by ettoregia** [rroemhild/docker-test-openldap#5]
Hi there, thanks for this repo.

I'm trying to execute the below ldapsearch but I always get 32 No such Result, any help would be really appreciated.

ldapsearch -x -h localhost -p 389  -D "cn=Hubert J. Farnsworth,ou=people,dc=planetexpress,dc=com" -w "professor" -b "dc=example,dc=com" -s sub '(objectClass=\*)' 'givenName=\*'

 LDAPv3
 base <dc=example,dc=com> with scope subtree
 filter: (objectClass=*)
 requesting: givenName=*

 search result
search: 2
result: 32 No such object

**Comment by rroemhild** [comment]
The last argument is for the attribute you wan't get back from the search result, so it should be only `givenName`:

`ldapsearch -x -h localhost -p 389 -D "cn=Hubert J. Farnsworth,ou=people,dc=planetexpress,dc=com" -w "professor" -b "dc=example,dc=com" -s sub '(objectClass=*)' givenName`

**Comment by ettoregia** [comment]
Ok many thanks

**Comment by rroemhild** [comment]
Your welcome
