### ISSUE TITLE
Custom Attribute possible?

### ISSUE THREAD

**Issue by regenrek** [rroemhild/docker-test-openldap#8]
Hi

I would like to add a custom String attribute for a person. Is this somehow possible. I just found the `msad.ldif` file but no luck yet.

Regards

**Comment by rroemhild** [comment]
Hi, you can add custom object classes and attributes. Just like the `msad.ldif` file. Add a new file to the `config` dir and add this file to `slapd-init.sh`.

**Comment by regenrek** [comment]
Thanks! It works now

**Comment by himito** [comment]
Hi @regenrek 

Could you please share an example of the `ldif` file? I tried to add a new attribute with no success :(

Thank you in advance
